language: node_js
node_js:
- '5'
script:
- npm run-script travis
before_script:
- npm install
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
  - secure: D4GVFSNWWGdInTmFYz2FtY7VT4cUiOdyfuO1fhaKELjwBoqevGgUN0t3G1gMOwt2q+B+FyYgbW59GGtIhfzjY4PGNOAHN4EKuVOLus9Wiq4cQqMJddt+nvf2f5sEnCAfWjN8VWwf819iTFpZPR9ri07i64Uo3G3GcrD29J96+Fa99pt8esBYcExJXkLev1mKUA+7r+KHlVYiO4MzxVhu24WyeSyz2qWnzUkdo06uTc6qTiDuKm9s1xiYAhDvNWGHRImR4tuYnXyCtD6kkj5CpSbXIoKxETSdp7iCLT0U5V21uGvJyuOEqrU2dHiT0yCVI/mLb96IfJaRRiEQL+RL7arntvSDtRMsvpsQSRw6RWb6Gir7zUCmQVIC7vtcQmtZvi6cmtG37OxQ6GQRDF0kbbfn9os7Jpzuo2LKMbQLIvwzMm/E3ihTzG78X6H9IGCaOiguR2cAm2oUSFroz+HwrTUEN5PULv3VrL1j0CcJHstsY1Dahma2RlIBaPIKUbo6aW99HzxTfPbbD1i4xNv2f4eVDhjL+UKUIEAcpieAHFCTv6yOhHsAyaVkXYlW2VfIjGt/PYR4wq/EG6RR0psSNnWsiuddsRgdSwKORfb2IOqw9Vyouu+sI0lp5cVnq9DR53x/0YDCb/OwNu5u/qbhrQHfPORvSvlCAqmAo96uwLo=
deploy:
  provider: heroku
  app: infinite-reef-57960
  api_key:
    secure: qX9Mj9e94SzsAIzLREelqL28MBbeN6eDVGs4dtGh+sOEDPrnntdH0CU1r/ti81ca0EUl0LKSAa8eCm6W9WGRMr5FSyGc7vtg+jx5Z7Sgumfkcy9nYV80U11i81zUHH/JJY7ZN/+zVMWYZPL2p24dic1ZYNGd6A1wtbi9abAhVLhyJphA7S+os6WURBQfp9ayp8UiNccUXOX14kgZSrHtciUxJxZQ/iSVT0jCgAc12fl1l6pVuT31FgFDQreyWzY9nRunQSKYFTiE/pXVbnxfrdQg8Up4DeAYU0dEfgLt0aMm6zGa9cymBx5CKP78QVJYEg9d1wSSLgNfzeFp+5+4VwllsDLVR7EhrY7o2qN591tXhAl2SnFtpsCn/StLeCtbiwzJjdNegoImTHhaszl3sCF9oCX6y5r3KKXSgdxQYVZVnGUgqKgcU+L+Ti40YR/w180E8kDyVV8WahUoAzPauGB1oIQxZyHI+wsEidnJ8Eg9KmsNd0G2rJSqXZhPh/xB50uE0B+elPCbmXqaQQNv0yrEPb3pg7UFkbczEw8mi5EHBbt9pl8giRRpx5kVYgYtMT36vqG5cMm6P+3D+tsTYyoVBAde6iRcRY3zX2H5jmpNDbLVODqxCeX4JlLFvtbYT0InpCurXHbYFGNMjDzx3VvKAS1KEg51WDwLn4EchGU=
